version: 2
jobs:
  build:
    branches:
      only:
        - develop
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: version injection
          command: |
            export GNEWCASH_BETA_VERSION="b${CIRCLE_BUILD_NUM}"
            sed -i "s/%%GNEWCASH_BETA_VERSION%/$GNEWCASH_BETA_VERSION/g" pyproject.toml
      - run:
          name: install poetry
          command: |
            pip install poetry
      - run:
          name: install dependencies
          command: |
            poetry install
      - run:
          name: run code linters
          command: |
            poetry run flake8 gnewcash
            poetry run pylint gnewcash
            poetry run mypy gnewcash
      - run:
          name: run unit tests
          command: |
            poetry run coverage run -m unittest discover
      - run:
          name: upload to test PyPI
          command: |
            poetry build
            poetry config repositories.testpypi https://test.pypi.org/legacy/
            poetry publish --repository testpypi --username $PYPI_USERNAME --password $PYPI_PASSWORD