# Stubs for gnewcash.file_formats.base (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import abc
from gnewcash.gnucash_file import GnuCashFile
from typing import Any

class BaseFileReader(abc.ABC, metaclass=abc.ABCMeta):
    @classmethod
    @abc.abstractmethod
    def load(cls: Any, *args: Any, **kwargs: Any) -> GnuCashFile: ...

class BaseFileWriter(abc.ABC, metaclass=abc.ABCMeta):
    @classmethod
    @abc.abstractmethod
    def dump(cls: Any, *args: Any, **kwargs: Any) -> None: ...

class BaseFileFormat(BaseFileReader, BaseFileWriter, abc.ABC):
    @classmethod
    def load(cls: Any, *args: Any, **kwargs: Any) -> GnuCashFile: ...
    @classmethod
    def dump(cls: Any, *args: Any, **kwargs: Any) -> None: ...
