name: Dev

on:
  push:
    tags:
      - b*
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version:
          - {os: macOS-latest, python: '3.11.x'}
          - {os: macOS-latest, python: '3.12.x'}
          - {os: ubuntu-latest, python: '3.9.x'}
          - {os: ubuntu-latest, python: '3.10.x'}
          - {os: ubuntu-latest, python: '3.11.x'}
          - {os: ubuntu-latest, python: '3.12.x'}
          - {os: windows-latest, python: '3.9.x'}
          - {os: windows-latest, python: '3.10.x'}
          - {os: windows-latest, python: '3.11.x'}
          - {os: windows-latest, python: '3.12.x'}
    runs-on: ${{matrix.version.os}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.version.python}}
          architecture: x64
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Run code linters
        run: |
          poetry run flake8 gnewcash
          poetry run pylint gnewcash
          poetry run mypy gnewcash
      - name: Run unit tests
        run: |
          poetry run pytest --cov=gnewcash tests/
  publish-test-pypi:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.x'
          architecture: x64
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Replace setup.py version
        run: |
          version_num=$(echo "${{github.ref_name}}" | sed 's/^b//g')
          echo "Using version ${version_num}"
          sed -i "s/version='0.0.0'/version='${version_num}'/" setup.py
          sed -i 's/version = "0.0.0"/version="'"${version_num}"'"/' pyproject.toml
          echo "--------------------------------------------------------------------------------"
          echo "SETUP.PY"
          cat setup.py
          echo "--------------------------------------------------------------------------------"
          echo "PYPROJECT.TOML"
          cat pyproject.toml
          echo "--------------------------------------------------------------------------------"
      - name: Publish to Test PyPI
        run: |
          poetry build
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry publish --repository testpypi --username ${{secrets.TEST_PYPI_USERNAME}} --password ${{secrets.TEST_PYPI_PASSWORD}}
  update-documentation:
    needs: publish-test-pypi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.x'
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Make sphinx documentation
        run: |
          cd sphinx
          poetry run make clean
          poetry run make html
          cp -rf _build/html/* ../docs
      - name: Commit updated documentation
        run: |
          set +e
          
          echo "Setting user name..."
          git config --global user.name 'Paul Bromwell Jr'
          echo "Setting e-mail..."
          git config --global user.email 'pbromwelljr@proton.me'
          echo "Adding docs to index..."
          git add docs/
          
          # Make sure we only commit if there's something to commit.
          echo "Checking git diff index status..."
          git diff-index --quiet HEAD 2>/dev/null 1>&2
          if [[ $? -ne 0 ]]; then
            echo "Committing..."
            git commit -m "Sphinx documentation update"
            echo "Pushing..."
            git push
          fi
