name: Dev

on:
  push:
#    tags:
#      - b*
    branches:
      - develop
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version:
          - {os: macOS-latest, python: '3.11.x'}
          - {os: macOS-latest, python: '3.12.x'}
          - {os: ubuntu-latest, python: '3.9.x'}
          - {os: ubuntu-latest, python: '3.10.x'}
          - {os: ubuntu-latest, python: '3.11.x'}
          - {os: ubuntu-latest, python: '3.12.x'}
          - {os: windows-latest, python: '3.9.x'}
          - {os: windows-latest, python: '3.10.x'}
          - {os: windows-latest, python: '3.11.x'}
          - {os: windows-latest, python: '3.12.x'}
    runs-on: ${{matrix.version.os}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.version.python}}
          architecture: x64
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Run code linters
        run: |
          poetry run flake8 gnewcash
          poetry run pylint gnewcash
          poetry run mypy gnewcash
      - name: Run unit tests
        run: |
          poetry run pytest --cov=gnewcash tests/
  publish-test-pypi:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.x'
          architecture: x64
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Generate stubs
        run: |
          poetry run stubgen -p gnewcash
          cp -r out/gnewcash/* gnewcash/
          rm -rf out/
      - name: Make sphinx documentation
        run: |
          cd sphinx
          poetry run make clean
          poetry run make html
          cp -rf _build/html ../docs
      - name: Commit updated documentation
        run: |
          git config --global user.name 'Paul Bromwell Jr'
          git config --global user.email 'pbromwelljr@proton.me'
          git add docs/
          git commit -m "Sphinx documentation update"
          git push
      - name: Replace setup.py version
        run: |
          version_num=$(echo "${{github.ref_name}}" | sed 's/^b//g')
          echo "Using version ${version_num}"
          sed -i "s/version='PLACEHOLDER'/version='${version_num}'/" setup.py
          cat setup.py
#      - name: Publish to Test PyPI
#        run: |
#          poetry build
#          poetry config repositories.testpypi https://test.pypi.org/legacy/
#          poetry publish --repository testpypi --username ${{secrets.PYPI_USERNAME}} --password ${{secrets.PYPI_PASSWORD}}
