name: Pull Request

on:
  pull_request:
    types: [opened, reopened]
jobs:
  lint-and-test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - {os: macOS-latest, python: '3.11.x'}
          - {os: macOS-latest, python: '3.12.x'}
          - {os: ubuntu-latest, python: '3.9.x'}
          - {os: ubuntu-latest, python: '3.10.x'}
          - {os: ubuntu-latest, python: '3.11.x'}
          - {os: ubuntu-latest, python: '3.12.x'}
          - {os: windows-latest, python: '3.9.x'}
          - {os: windows-latest, python: '3.10.x'}
          - {os: windows-latest, python: '3.11.x'}
          - {os: windows-latest, python: '3.12.x'}
    runs-on: ${{matrix.version.os}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.version.python}}
          architecture: x64
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run code linters
        run: |
          poetry run flake8 gnewcash
          poetry run pylint gnewcash
          poetry run mypy gnewcash
      - name: Run unit tests
        run: |
          poetry run pytest --cov=gnewcash tests/
